### ISSUE TITLE
Move the comment block from `worker/index.js` to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by SerpentBytes** [humphd/my-photohub#12]
## Description
This issue is related to the PR created for #1. We want to extract the auto-generated comment block at the top of the `worker/index.js` and add it to `CONTRIBUTING.md`. 

The comment block looks as follows:

```node
 *
  * - Run `npx wrangler dev src/index.js` in your terminal to start a development server
  * - Open a browser tab at http://localhost:8080/ to see your worker in action
  * - Run `npx wrangler publish src/index.js --name my-worker` to publish your worker
  *
  * Learn more at https://developers.cloudflare.com/workers/
  */
```

### Additional Information
**Note:** The file has undergone some changes since it was first generated, so some of the information in the comment block, such as the `file path` and `port` number, may be outdated.

**Comment by rudychung** [comment]
Could I give this a try? I'm not 100% sure what is wanted though, just moving the block comment content over to `CONTRIBUTING.md`?
