### ISSUE TITLE
Add `tests` for `worker` using `jest`

### ISSUE THREAD

**Issue by SerpentBytes** [humphd/my-photohub#13]
## Description
This issue is related to the PR created for #1.

We need to write tests for our Cloudflare `workers` using `jest`. The `worker/index.test.js` was automatically generated along with `worker/index.js` using a script.

### Additional Information
 The test file is outdated since the `worker/index.js` file has undergone significant changes since it was initially created.

**Comment by devils2ndself** [comment]
I'd like to give this a try! Could I get assigned to this one?

**Comment by SerpentBytes** [comment]
Go ahead.
