### ISSUE TITLE
Design a gallery view for showing a user's images

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#2]
We need a gorgeous web page to show a user's photos.  There's lots of prior art we can use for this, consider how Google Photos does it:

![image](https://user-images.githubusercontent.com/427398/196782660-5a977e3c-8e2a-4047-97c7-1e9465e83626.png)

I think we need some kind of tile view to show all the images at once, and the ability to click an image and see it full.  I'm sure there are some good open source options for doing this.

**Comment by LostButton** [comment]
Do you mind if I take a shot at this for release 0.3?

**Comment by humphd** [comment]
@LostButton all yours, go for it.
