### ISSUE TITLE
Create HTML page using GitHub Actions

### ISSUE THREAD

**Issue by SerpentBytes** [humphd/my-photohub#31]
## Description
When the images are optimized for the web, we want to create a new HTML web page using [GitHub Actions](https://docs.github.com/en/actions), which will eventually be stored in the repo we created on behalf of the user in #1

**Comment by batunpc** [comment]
This seems to be related https://github.com/humphd/my-photohub/issues/5

**Comment by SerpentBytes** [comment]
> This seems to be related https://github.com/humphd/my-photohub/issues/5

That's why I labelled it as “duplicate” since @humphd can delete issues.

**Comment by humphd** [comment]
We don't delete, we prefer to close issues.  Go ahead and close if this is not needed, you should have rights.
