### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#39]
A bunch of cool work has happened on this project, and I'm not the primary developer.  I'd like to transfer the repo to a maintainer (or maintainers) who want to keep it going.

If any of the existing contributors wants to take over ownership of this repo, please leave a comment below and I'll transfer it to you.  If more than one wants to do it, we can create an ORG and you can share it.

@LostButton @SerpentBytes @rudychung @anshul137 @batunpc @saminarp @devils2ndself

**Comment by SerpentBytes** [comment]
@humphd, could you make it part of Seneca-CDOT or some other org, like some other internal projects, and make the contributors, plus yourself (since you started the project), the maintainers?

**Comment by SerpentBytes** [comment]
@humphd As many of us don't have prior experience with Cloudflare workers, it would be a great way to gain experience with workers if we continue working on this project. Just a thought.

**Comment by batunpc** [comment]
> @humphd, could you make it part of Seneca-CDOT or some other org, like some other internal projects, and make the contributors, plus yourself (since you started the project), the maintainers?

I also would like to see `my-photohub` under [Seneca-CDOT](https://github.com/Seneca-CDOT)

**Comment by CDPhu** [comment]
Yes, I also feel like it should go under Seneca-CDOT

**Comment by SerpentBytes** [comment]
@humphd I would like to maintain this project.

**Comment by humphd** [comment]
OK, this has been transferred to Seneca-CDOT.
