### ISSUE TITLE
Create a PWA UI for accessing the service

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#4]
The main way of interacting with **My Photohub** will be a web page.  Specifically, a Progressive Web App (PWA) that users can install to their phone or computer.

It probably makes sense to create this using React and one of the various React frameworks (next.js, create-react-app, etc)

**Comment by batunpc** [comment]
Hey @humphd, I would like to tackle this!

**Comment by batunpc** [comment]
I am working on this and have questions regarding PWA. Currently I have react app running on localhost but I'm not sure how to install it as PWA through localhost as the app is not hosted.

**Comment by SerpentBytes** [comment]
I think @humphd wants us to use the serverless approach using Cloudflare service workers, both in the front end and back end. See this example to setup a React PWA project using Cloudflare service workers:
https://github.com/cloudflare/workers-react-pwa-example
https://blog.cloudflare.com/serverless-pwa-react-cloudflare-workers/ 

@humphd, correct me if I am wrong.
