### ISSUE TITLE
Create the app's UI

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#6]
This is connect to #4, but where that issue is about creating the PWA infrastructure, this issue is about making the UI that users interact with when creating their page.

We need to be able to do at least the following:

- give a name for the project (also used to create the repo name).  For example: "Hike October 2022" and the repo name might be "hike-october-2022"
- allow users to pick photos to use (e.g., from their phone's camera roll, or uploaded from their computer)
- Possibly set other fields of info (date, description, etc.)

This data will get used to generate the site

**Comment by rudychung** [comment]
Hi. I'd like to work on this, but I'm not entirely clear on how the app UI will interact with the PWA infrastructure. Am I right in thinking that the UI will just be built up from the existing infrastructure in React?

**Comment by humphd** [comment]
Correct, you'd be extending what's already there.

**Comment by rudychung** [comment]
Currently the main page looks like:
![image](https://user-images.githubusercontent.com/61764259/204908510-422e5cf9-33e8-46a1-ade3-a8558bc0e9fc.png)

The wireframe of what I'm planning to change the layout to:
![image](https://user-images.githubusercontent.com/61764259/204909003-8bf42c5d-f573-4699-97c0-102d535bee13.png)

@humphd @batunpc @saminarp 
Any feedback or desired additions to my plan?
