### ISSUE TITLE
Figure out how to "upload" resources to GitHub

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#7]
When a user picks their photos and specifies their project's metadata #6 , we need to "upload" it to the new GitHub repo that we build for them (#1).  We'll have to make a commit to git on their behalf, and `push` to GitHub, or somehow use the GitHub API to create a commit with all the necessary files.

Once this commit is made, the GitHub Actions (#3 and #5) should kick in and create everything.

**Comment by saminarp** [comment]
Hi,

I would like to give this issue a try! Thank you.
